services:
  - type: web
    name: my-portfolio
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: USER_EMAIL
        sync: false
    disk:
      name: my-portfolio
      mountPath: /
      sizeGB: 1